### ISSUE TITLE
[INFO] steps to active APN and data flow

### ISSUE THREAD

**Issue by marabesi** [thehapyone/BareBoneSim800#2]
First of all, thank you VERY MUCH for this wonderful lib which I've learned a lot reading the source code.

My question is how did you manage to get the flows? For example, in the following code you had to execute a series of commands to get the locations working:

````c
this->SoftwareSerial::print (F(" AT+SAPBR=3,1,\"CONTYPE\",\"GPRS\" \r\n" ));
    _buffer=_readSerial();  // set bearer parameter
    this->SoftwareSerial::print (F(" AT+SAPBR=3,1,\"APN\",\"internet\" \r\n" ));
    _buffer=_readSerial();  // set apn
    this->SoftwareSerial::print (F(" AT+SAPBR=1,1 \r\n"));
    delay(1200);
    _buffer=_readSerial();			// activate bearer context
    this->SoftwareSerial::print (F(" AT+SAPBR=2,1\r\n "));
    delay(3000);
    _buffer=_readSerial(); 		
````

First enable the GPRS, second setting the APN and so one, how did you know that?

I've found a [PDF](https://www.elecrow.com/download/SIM800%20Series_AT%20Command%20Manual_V1.09.pdf) where I could understand better all the commands, but not the flows.

**Comment by thehapyone** [comment]
The flows are described in the device datasheet. I actually read it from the beginning to the end. 
For example, the commands for getting the location are described in the image attached.
![flow syntax](https://user-images.githubusercontent.com/8368470/36281903-a6e40718-129f-11e8-9736-3a8b5c68f2c1.PNG)
![flow syntax2](https://user-images.githubusercontent.com/8368470/36282048-1cdf482e-12a0-11e8-8c06-50ced198d310.PNG)

So yeah, that's how I got the flows working.

**Comment by marabesi** [comment]
Cool, just closed the issue since you gave me the answer :)

**Comment by marabesi** [comment]
Obs: I've added the pdf link for further reference
