### ISSUE TITLE
Is it support HTTP Post method ?

### ISSUE THREAD

**Issue by dhsont** [thehapyone/BareBoneSim800#4]
HI,

Is it support HTTP Post method ?

**Comment by thehapyone** [comment]
Yeah, it does support HTTP Post. 
See the examples httpClient and Pubnub Post
https://github.com/thehapyone/BareBoneSim800/blob/master/examples/

**Comment by xLarry** [comment]
I just scanned through the above mentioned examples and the corresponding source code and it does not seem as if the library would support a HTTP POST request.

This assumption is based on the following indicators:

- the `sendHTTPData()` doesn't accept any parameters to set the HTTP action
- the `sendHTTPData()` method issues an `AT+HTTPACTION=0` command in [line 539](https://github.com/thehapyone/BareBoneSim800/blob/50050b08d4b1de81a5166bcc49e2eb3125b6ac5d/BareBoneSim800.cpp#L539). The [SIM800 AT Command Manual](https://www.elecrow.com/download/SIM800%20Series_AT%20Command%20Manual_V1.09.pdf) (page 260) tells us that `AT+HTTPACTION=0` will trigger a GET request.

However, the library looks well coded and documented on first sight and is exactly what I am looking for right now. I might try to add HTTP POST functionality on my own and will share my progress if you are interested.

**Comment by thehapyone** [comment]
Yeah, you right. I thought HTTP Post was added to the Library. Let me know if you come up with anything, and I won't be able to add that functionality at this point in time. 
Depending on the type of application, one might be able to get away using only the GET method.
