### ISSUE TITLE
including call functions 

### ISSUE THREAD

**Issue by ste2761** [thehapyone/BareBoneSim800#8]
Hey, can someone please include the call functions. That would help me a lot for my project.  Because other lib´s are not  that  well with sending sms.

**Comment by thehapyone** [comment]
The Call features are currently not supported in this library version. Unfortunately, I can't add that anytime soon, because I don't have access to any hardware unit around. 
This tutorial could be helpful for your case - https://lastminuteengineers.com/sim800l-gsm-module-arduino-tutorial/

**Comment by ste2761** [comment]
Hey,  thanks for the link, it is really helping me out.
